fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\1.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\2.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\3.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\4.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\5.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\6.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\7.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\8.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\9.txt", "w")
fp = open("D:\\COLLEGE\\Python Lab\\ques2\\AllFiles\\10.txt", "w")
print("Files ban gyi (located in AllFiles folder)")